# Name of Action
name: 'Workflows'

# Controls when action will get triggered 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:  

# This workflow contains a single job called "build"
  build:
  
# The type of runner that the job will run on
    runs-on: ubuntu-latest
    
#    defaults:
#      run:
#        shell: bash

    steps:
#    - name: Checkout
#      uses: actions/checkout@v2
      
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: ${{ secrets.SA_KEY }}

    - name: Set up gcloud Cloud SDK environment
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
         sa_key: ${{ secrets.SA_KEY }}
         project_id: ${{ secrets.PROJECT_ID }}
         export_default_credentials: true

    - run: |-
        gcloud components install beta 
        gcloud beta workflows deploy Test-WF --location us-central1 --source .github/workflows/workflow.yaml --quiet
        gcloud workflows execute Test-WF --data='{"machinetype":"e2-small","instance":"${{ github.event.pull_request.user.login }}-instance","project":"${{ secrets.PROJECT_ID }}","zone":"us-central1-a"}'
