main:
    params: [args]

    steps:
    - init: 
        assign:
        - project: ${args.project}
        - zone: ${args.zone}
        - machineType: ${args.machinetype}
        - instanceName: ${args.instance}
        
 # create vm

    - create_machine:
        call: googleapis.compute.v1.instances.insert
        args:
          project: ${project}
          zone: ${zone}
          body:
            name: ${instanceName}
            machineType: ${"zones/" + zone + "/machineTypes/" + machineType}
            disks:
            - initializeParams:
                sourceImage: "projects/debian-cloud/global/images/debian-10-buster-v20201112"
              boot: true
              autoDelete: true
            networkInterfaces:
            - network: "global/networks/default"

    - someSleep:
        call: sys.sleep
        args:
          seconds: 28800
          
    - delete_VM:
        call: googleapis.compute.v1.instances.delete
        args:
          project: ${project}
          instance: ${instanceName}
          zone: ${zone}
        result: delete_VM_result
    - last:
        return: ${delete_VM_result}
