name: Deploy Cloud Workflow
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy Cloud Workflow
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.PROJECT_ID }}
        service_account_key: ${{ secrets.SA_KEY }}
        export_default_credentials: true
        
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: ${{ secrets.SA_KEY }}
        
    - name: Use gcloud CLI
      run: |
        gcloud workflows deploy myWorkflowFromGitHub \
        --location us-central1 \
        --source ./.github/workflows/flow.yaml \
        --project ${{ secrets.PROJECT_ID }} \
        --labels "commit-sha=${{ github.sha }}"
